# html lang
language: en

# main menu navigation
menu:
  About: https://www.thosynpax.com/
  Billion-Bytes: https://thosynpax.com/bytes
  Meeting: https://calendar.app.google/i8s7Mao11AY28HVH6

# Social
social:
  email: me@thosynpax.com
  twitter: https://twitter.com/thosynpax
  linkedin: https://www.linkedin.com/in/thosyn-pax/
  github: https://github.com/ThosynPax
  instagram: https://instagram.com/thosynpax

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
  - /css/iLiKE.css

logo:
  - /images/logo.png

# scripts loaded in the end of the body
scripts:
  - /js/iLiKE.js

# Site creation time
since: 2024

# Blog auto_excerpt
auto_excerpt:
  enable: true
  length: 150

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: 6E5zTbTljdUbVW2WkXPsXGJk-gzGzoHsz
  app_key: 0vsyDKfNpeSECAI70J794ugv
